server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://auth-db:5432/authdb
    username: auth_user
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true

security:
  jwt:
    secret: thisisaverysecuresecretkeyforjwtmustbe32bytes!
    expiration: 3600000 # 1 час в миллисекундах
