server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://auth-db:5432/authdb
    username: ${AUTH_DATASOURCE_USERNAME}
    password: ${AUTH_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET}
    expiration: 3600000
