services:

  auth-db:
    image: postgres:16
    container_name: auth-db
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: ${AUTH_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${AUTH_DATASOURCE_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: auth-service
    ports:
      - "8081:8080"
    depends_on:
      - auth-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/authdb
      SPRING_DATASOURCE_USERNAME: ${AUTH_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${AUTH_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SECURITY_JWT_SECRET: ${SECURITY_JWT_SECRET}
      SECURITY_JWT_EXPIRATION: 3600000

  license-db:
    image: postgres:16
    container_name: license-db
    environment:
      POSTGRES_DB: licensedb
      POSTGRES_USER: ${LICENSE_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${LICENSE_DATASOURCE_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - license_data:/var/lib/postgresql/data

  license-service:
    build:
      context: .
      dockerfile: license-service/Dockerfile
    container_name: license-service
    ports:
      - "8082:8080"
    depends_on:
      - license-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://license-db:5432/licensedb
      SPRING_DATASOURCE_USERNAME: ${LICENSE_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${LICENSE_DATASOURCE_PASSWORD}
      SECURITY_JWT_EXPIRATION: 3600000
      SECURITY_JWT_SECRET: ${SECURITY_JWT_SECRET}
      SECURITY_SYSTEM_TOKEN: ${SECURITY_SYSTEM_TOKEN}

volumes:
  auth_data:
  license_data:
