server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://license-db:5432/licensedb
    username: license_user
    password: secret

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

security:
  jwt:
    secret: thisisaverysecuresecretkeyforjwtmustbe32bytes!
    expiration: 3600000
